### ISSUE TITLE
how to parse non-tuple struct

### ISSUE THREAD

**Issue by Paulswith** [RReverser/serde-xml-rs#116]
I have a XML data like this:
```xml
<?xml version="1.0" encoding="utf-8"?>

<string xmlns="http://tempuri.org/">IAmContent</string>
```

As I understanding, I define a struct below:
```rust
#[derive(Debug, serde::Deserialize)]
#[serde(rename = "string")]
pub struct ContentWrap(String);
```

but the result is: 
invalid type: map, expected tuple struct ResponseWrap

**Comment by punkstarman** [comment]
Thank you for filing this issue.

The `ContentWrap` structure is in a newtype struct because the constructor takes only one argument. The constructor of a tuple struct takes two or more arguments and that of a unit structs takes no arguments.

It appears that there is a bug in the handling of newtype structs. I will submit a pull request to fix this.
