### ISSUE TITLE
Deserializing lists

### ISSUE THREAD

**Issue by jrozner** [RReverser/serde-xml-rs#17]
The following can be sucessfully deserialized into the following structs.
```xml
<root>
  <someTag>
  </someTag>
  <serviceList>
    <service>
      ...
    </service>
    <service>
      ...
    </service>
  </serviceList>
</root>
```
```rust
struct Root {
    some_tag: SomeTag,
    service_list: ServiceList,
}
struct ServiceList {
    service: Vec<Service>,
}
struct Service {
}
```

However, is it possible to avoid creating the ServiceList struct and just make the service_list member a Vec<Service> instead?

**Comment by RReverser** [comment]
I don't think so, after all `serviceList` is a separate element on the tree and could potentially have own attributes which would be otherwise lost.

Your best bet can be implementing custom `Deserialize` on `Root` that would deserialize content into an internal structure and convert to a desired format.
